# 3-1. Numpy

In [1]:
import numpy as np
np.__version__

'1.18.1'

## ndarray, ndim

- Numpy는 ndarray (N-Dimensional Array) 그 자체이다. Numpy는 ndarray로 돌아가는 라이브러리이다.
- 예를 들어 이미지의 경우, H x W x C (Channel, 컬러) 3차원.

### 1D ndarray

In [2]:
nd1 = np.array([1, 2, 3, 4])

In [3]:
print(nd1)

[1 2 3 4]


In [4]:
nd1.ndim

1

### 2D ndarray

In [5]:
nd2 = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
print(nd2)

[[1 2 3]
 [4 5 6]]


In [7]:
nd2.ndim

2

### 3D ndarray

In [8]:
nd3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
                 [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])

In [9]:
print(nd3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


In [10]:
nd3.ndim

3

### 4D ndarray

In [11]:
nd4 = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
                [[[9, 10], [11, 12]], [[13, 14], [15, 16]]],
                [[[17, 18], [19, 20]], [[21, 22], [23, 24]]]])

In [12]:
print(nd4)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]


 [[[17 18]
   [19 20]]

  [[21 22]
   [23 24]]]]


In [13]:
nd4.ndim

4

---

## dtype

- 정수는 기본으로 **int32**, 실수는 기본으로 **float64**로 할당됨.
- `np.array()`에 dtype 파라미터 줘서 dtype 변경 가능. 또는 `nd2.astype(np.float32)` 같이 하면 dtype 변환된 ndarray 나옴.
- TF에서도 타입 똑같다. (Tensor라는 것도 결국엔 Numpy의 ndarray를 기반으로 하니까!)

In [14]:
nd1 = np.array([1.0, 2.1, 3.0, 4.2])
nd1.dtype

dtype('float64')

In [15]:
nd2 = np.array([[1, 2, 3], [4, 5, 6]])
nd2.dtype

dtype('int32')

In [16]:
nd2 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
nd2.dtype

dtype('float32')

In [17]:
nd2 = np.array([[1, 2, 3], [4, 5, 6]], dtype='float64')
nd2.dtype

dtype('float64')

In [18]:
nd2.astype(np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [19]:
nd2.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
nd1 = nd1.astype('int32')
nd1.dtype

dtype('int32')

---

## shape, size

- ML, DL에서 입력 데이터의 shape를 맞추고 확인하는 과정은 매우 중요하다. 데이터를 읽으면, 가장 먼저 shape를 체크할 것.
- `(4,)` 같이 1차원 ndarray의 경우, 콤마 뒤에 1이 생략되어있다고 생각하자.
= size는 그냥 전체 element 개수. shape 각 숫자 모두 곱하면 당연히 size가 된다.

In [21]:
nd1.shape

(4,)

In [22]:
nd2.shape

(2, 3)

In [23]:
nd3.shape

(2, 4, 3)

In [24]:
nd4.shape

(3, 2, 2, 2)

## reshape

- shape를 바꿔주어야할 때가 많다.
- `ndarray.reshape()` : shape 형식 tuple을 입력받아서 reshape하는데, 이 때 size가 맞아야 한다.

In [25]:
nd3.shape

(2, 4, 3)

In [26]:
nd4.shape

(3, 2, 2, 2)

In [27]:
new_nd3 = nd4.reshape((2,4,3))

In [28]:
new_nd3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [29]:
new_nd3.shape

(2, 4, 3)

In [30]:
new_nd2 = nd3.reshape((4,6))

In [31]:
new_nd2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [32]:
new_nd2.shape

(4, 6)

In [33]:
new_nd1 = nd3.reshape((24,))

In [34]:
new_nd1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [35]:
new_nd1.shape

(24,)

## zeros, ones, arrange

In [36]:
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [40]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [41]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

---

## Vectorize operaion (벡터화 연산)

- ndarray끼리 +, -, *, / 지원
- 같은 위치의 원소끼리 (element-wise) 연산이 수행됨

In [42]:
op1 = np.array([1, 2, 3, 4, 5, 6])

In [43]:
op1

array([1, 2, 3, 4, 5, 6])

In [44]:
op1 = op1.reshape(3, 2)

In [45]:
op1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
op2 = np.array([2] * 6)

In [47]:
op2

array([2, 2, 2, 2, 2, 2])

In [48]:
op2 = op2.reshape(3, 2)

In [49]:
op2

array([[2, 2],
       [2, 2],
       [2, 2]])

In [50]:
op1 + op2

array([[3, 4],
       [5, 6],
       [7, 8]])

In [51]:
op1.shape

(3, 2)

In [52]:
op1 - op2

array([[-1,  0],
       [ 1,  2],
       [ 3,  4]])

In [53]:
op1 * op2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [54]:
op1 / op2

array([[0.5, 1. ],
       [1.5, 2. ],
       [2.5, 3. ]])

---

## Broadcasting

- ndarray끼리 연산 시, 연산이 가능한 형태로 자동 reshape 후, 반복된 값으로 자동 할당해서 연산을 수행해 줌.
- 예를 들어, ndarray `[0, 1, 2]`랑 int `5` 더하면? ==> ndarray `[5, 6, 7]`이 된다!
- int `5`가 ndarray `[5, 5, 5]`로 broadcast된 것.

In [55]:
np.arange(3)

array([0, 1, 2])

In [56]:
np.arange(3) + 5

array([5, 6, 7])

In [57]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
np.ones((3, 3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [59]:
np.arange(3).reshape(3,1)

array([[0],
       [1],
       [2]])

In [60]:
np.arange(3).reshape(3,1) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])